### ISSUE TITLE
Addon Beta announcement thread

### ISSUE THREAD

**Issue by Sandmann79** [Sandmann79/xbmc#700]
In this issue, new addon beta versions will be published in the future.

Currently no beta version available

**Comment by yrp888** [comment]
I can confirm that Beta 3 has fixed the lost categories issue (#698) , as well as a Login Error (#699).

Great work and thank you!

**Comment by fhoellwarth** [comment]
I can confirm Beta 3 works for me on Kodi 20.2 (OSMC 2023.07-1). Menus are displayed again.
Thank you so much!

**Comment by Paco8** [comment]
I've just tested the android api but I'm afraid the watchlist doesn't work for me. It shows some folders (all videos, tv shows, channels...) but all are empty.

The watchlist doesn't work correctly either when using "website" as data source, it only display the first 20 items in the movies folder.

**Comment by ntropy83** [comment]
Works great again and more structure in the folders now. DE, Kodi 20.2 (Arch Linux with LTS kernel), Udoo Bolt Gear (Ryzen V1605B).

**Comment by Ronny-nerd** [comment]
Hello Sandmann, will there be a new beta version soon after beta 3?

**Comment by MiyasakiYoshi** [comment]
Fantastic that you guys have gone over to the mobile API. It will be way smoother navigation. Annoying though that the endpoints seems very random. This is the one that I got with Prime Video Nordic: https://abzq7aq4866p.eu.api.amazonvideo.com/ when using emulator on my PC. I get too many options when using the beta. I should only have access to Movies and Series.

**Comment by Sandmann79** [comment]
Beta 4 is available for testing at first post.

@Paco8 with this beta correct content should be displayed

**Comment by 27hectormanuel** [comment]
Support for IPTV Merge should be added for Freevee and Prime Live channels

**Comment by Atomisirsi** [comment]
Unfortunately, Beta 4 seems not to work with Nexus 20.2 anymore:
[amazon-vod.log](https://github.com/Sandmann79/xbmc/files/12640111/amazon-vod.log)

**Comment by Sandmann79** [comment]
@Atomisirsi oh, forget to test this part of code. You can bypass this by disabling views at settings. Will be fixed in the next days

**Comment by Sandmann79** [comment]
First post has been updated with the fixed Betas

**Comment by Ronny-nerd** [comment]
Thanks Sandmann79 ...the new corrected Plugin.video.amazon-test-0.9.9.beta4+matrix.1.zip now works without problems.

**Comment by Paco8** [comment]
I'm afraid the beta4 doesn't work for me on Kodi 18 if I enable the android api:

```
2023-09-22 16:09:28.838 T:140279403140864  NOTICE: [Amazon VOD] Connect to SignIn Page
2023-09-22 16:09:28.841 T:140279403140864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'str' object has no attribute 'hex'
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/default.py", line 7, in <module>
                                                EntryPoint()
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 71, in EntryPoint
                                                _g.pv.BrowseRoot()
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/android_api.py", line 67, in BrowseRoot
                                                self.getPage(root=True)
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/android_api.py", line 121, in getPage
                                                resp = getURL('%s?%s%s' % (url, self.defparam, params), useCookie=MechanizeLogin(True), headers=self._g.headers_android)
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/common.py", line 356, in MechanizeLogin
                                                return LogIn(preferToken)
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/login.py", line 369, in LogIn
                                                clientid = (user['deviceid'].encode() + b'#A1MPSLFC7L5AFK').hex()  # + _g.dtid_android.encode()).hex()
                                            AttributeError: 'str' object has no attribute 'hex'
                                            -->End of Python script error report<--
```

**Comment by James62370** [comment]
With beta3 I'm getting 4K, but on beta4 I only get Standard Def

**Comment by Sandmann79** [comment]
@Paco8 issue has been fixed with 953590ad41105edc0a55317481ed1ec949fe1fef

@James62370 there is a new setting under Playback "Widevine L1 certified device", which is deactivated by default. After activating it, HD should be available again.

**Comment by Paco8** [comment]
> @Paco8 issue has been fixed with [953590a](https://github.com/Sandmann79/xbmc/commit/953590ad41105edc0a55317481ed1ec949fe1fef)
> 

I'm afraid it's still not working with the android api:

```
2023-09-26 15:25:09.560 T:139684114249472  NOTICE: [Amazon VOD] Login
2023-09-26 15:25:09.561 T:139684114249472  NOTICE: [Amazon VOD] Retrieve territoral config
2023-09-26 15:25:09.574 T:139684114249472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'supported_langs'
                                            Traceback (most recent call last):
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/default.py", line 7, in <module>
                                                EntryPoint()
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 71, in EntryPoint
                                                _g.pv.BrowseRoot()
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/android_api.py", line 67, in BrowseRoot
                                                self.getPage(root=True)
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/android_api.py", line 121, in getPage
                                                resp = getURL('%s?%s%s' % (url, self.defparam, params), useCookie=MechanizeLogin(True), headers=self._g.headers_android)
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/common.py", line 322, in MechanizeLogin
                                                return LogIn(preferToken)
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/login.py", line 337, in LogIn
                                                user = getTerritory(loadUser(empty=True))
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/login.py", line 68, in getTerritory
                                                loc = ','.join(x[0] for x in _g.supported_langs)
                                              File "/home/user/.kodi/addons/plugin.video.amazon-test/resources/lib/common.py", line 133, in __getattr__
                                                return self._globals[name]
                                            KeyError: 'supported_langs'
                                            -->End of Python script error report<--
```

**Comment by Sandmann79** [comment]
@Paco8 sorry for the ongoing difficulties, should be corrected with 573933811dbfb6672977e2b662cc12b4de8d093c

**Comment by Sandmann79** [comment]
The next beta was attached to the start post. Hopefully the last before the release

**Comment by Atomisirsi** [comment]
Unfortunately, I found an issue with the Fanart Update in 0.9.9beta5:
```
2023-10-01 17:56:39.613 T:5987     info <general>: [Amazon VOD] Starting Fanart Update
2023-10-01 17:56:39.626 T:5987     info <general>: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/mobile/getDataByTransform/v1/android/atf/v3.jstl?deviceTypeID=A43PXU4ZN2AL1&firmware=fmw:22-app:3.0.351.3955&softwareVersion=351&priorityLevel=2&format=json&featureScheme=mobile-android-features-v11&deviceID=7b6356e9d478429f86124f2de6d84fbc&version=1&screenWidth=sw800dp&osLocale=de_DE&uxLocale=de_DE&supportsPKMZ=false&isLiveEventsV2OverrideEnabled=true&swiftPriorityLevel=critical&itemId=amzn1.dv.gti.9aaffebb-576e-d355-a2d4-9ed14731e7ab&capabilities=
2023-10-01 17:56:39.895 T:5987    error <general>: [Amazon VOD] Error reason: 500 error (TryAgain)
2023-10-01 17:56:39.896 T:5987     info <general>: [Amazon VOD] Switching UserAgent
2023-10-01 17:56:39.897 T:5987     info <general>: [Amazon VOD] Loading list of common UserAgents
2023-10-01 17:56:39.899 T:5987     info <general>: [Amazon VOD] getURL: http://www.skydubh.com/pub/useragents.json
2023-10-01 17:56:39.951 T:5987     info <general>: [Amazon VOD] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
2023-10-01 17:56:39.952 T:5987     info <general>: [Amazon VOD] Attempt #2
2023-10-01 17:56:39.952 T:5987     info <general>: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/mobile/getDataByTransform/v1/android/atf/v3.jstl?deviceTypeID=A43PXU4ZN2AL1&firmware=fmw:22-app:3.0.351.3955&softwareVersion=351&priorityLevel=2&format=json&featureScheme=mobile-android-features-v11&deviceID=7b6356e9d478429f86124f2de6d84fbc&version=1&screenWidth=sw800dp&osLocale=de_DE&uxLocale=de_DE&supportsPKMZ=false&isLiveEventsV2OverrideEnabled=true&swiftPriorityLevel=critical&itemId=amzn1.dv.gti.9aaffebb-576e-d355-a2d4-9ed14731e7ab&capabilities=
2023-10-01 17:56:40.062 T:5987    error <general>: [Amazon VOD] Error reason: 500 error (TryAgain)
2023-10-01 17:56:40.063 T:5987     info <general>: [Amazon VOD] Switching UserAgent
2023-10-01 17:56:40.065 T:5987     info <general>: [Amazon VOD] Loading list of common UserAgents
2023-10-01 17:56:40.067 T:5987     info <general>: [Amazon VOD] getURL: http://www.skydubh.com/pub/useragents.json
2023-10-01 17:56:40.121 T:5987     info <general>: [Amazon VOD] Using UserAgent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
2023-10-01 17:56:40.123 T:5987     info <general>: [Amazon VOD] Attempt #3
2023-10-01 17:56:40.125 T:5987     info <general>: [Amazon VOD] getURL: https://atv-ps-eu.amazon.de/cdp/mobile/getDataByTransform/v1/android/atf/v3.jstl?deviceTypeID=A43PXU4ZN2AL1&firmware=fmw:22-app:3.0.351.3955&softwareVersion=351&priorityLevel=2&format=json&featureScheme=mobile-android-features-v11&deviceID=7b6356e9d478429f86124f2de6d84fbc&version=1&screenWidth=sw800dp&osLocale=de_DE&uxLocale=de_DE&supportsPKMZ=false&isLiveEventsV2OverrideEnabled=true&swiftPriorityLevel=critical&itemId=amzn1.dv.gti.9aaffebb-576e-d355-a2d4-9ed14731e7ab&capabilities=
2023-10-01 17:56:40.226 T:5987    error <general>: [Amazon VOD] Error reason: 500 error (TryAgain)
2023-10-01 17:56:40.231 T:5987    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'season'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/default.py", line 7, in <module>
                                                       EntryPoint()
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 95, in EntryPoint
                                                       _g.pv.Route(mode, args)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/android_api.py", line 670, in Route
                                                       exec ('self._g.pv.{}()'.format(mode))
                                                     File "<string>", line 1, in <module>
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/android_api.py", line 418, in processMissing
                                                       self.retrieveArtWork(*data)
                                                     File "/storage/.kodi/addons/plugin.video.amazon-test/resources/lib/android_api.py", line 467, in retrieveArtWork
                                                       if 'season' in contentType and il['season'] == 1:
                                                                                      ~~^^^^^^^^^^
                                                   KeyError: 'season'
                                                   -->End of Python script error report<--

```

**Comment by Abb4d0n** [comment]
Any chance to get live events (Champions League) with 50 fps with the Android API?

**Comment by Sandmann79** [comment]
@Abb4d0n maybe there is a new parameter, but must first check if it breaks something.

**Comment by Abb4d0n** [comment]
50 fps may be limited to capable FireTV devices. Don't know if it uses the default Android API.

**Comment by Sandmann79** [comment]
With the Web API 50 fps works. Just haven't tested it yet, for lack of streams, under the Android API.

**Comment by cpassuel** [comment]
Just a dumb question:
I have beta v0.97 already installed on leia (RPi 4), should I only have to overwrite v0.97 files with those of the latest version or should I backup something before ?

**Comment by Paco8** [comment]
With an Android L1 device running Kodi 19, version 0.9.8 plays videos in HD, but version 0.9.9 plays them in SD. Enabling the 'Widevine L1 certified device' option doesn't fix it. I am using the 'website' API.

**Comment by Paco8** [comment]
When using 1.0.1~beta1 with Kodi 18 most of the audio tracks are "unknown".
![Captura de pantalla de 2023-10-27 13-27-21](https://github.com/Sandmann79/xbmc/assets/5084042/2b69b115-0a11-4884-8cca-70e5b390a518)

**Comment by Paco8** [comment]
I think the problem with language names in kodi 18 was introduced in commit https://github.com/Sandmann79/xbmc/commit/857803c660acea110d4c0c83f8384ddc066885f6

**Comment by Atomisirsi** [comment]
> Unfortunately, I found an issue with the Fanart Update in 0.9.9beta5:

This still persists in version 1.0.0, see my proposed solution in #714.

**Comment by KingNothing81** [comment]
Now with the public release version out … is the additional Captcha Resolver Addon still needed? Or is this functionality now included in the Prime Addon?

And thanks for keeping this running.

**Comment by Sandmann79** [comment]
@KingNothing81 the addon is still required, but it is installed automatically since the stable release

**Comment by Sandmann79** [comment]
@Paco8 please check if the bug is still present in the stable v1.0.1

**Comment by Paco8** [comment]
I'm afraid it's not fixed, I still get unknown audio tracks in kodi 18.

**Comment by Sandmann79** [comment]
@Paco8 i cannot reproduce it. Please upload a debug log and screenshot.

**Comment by Paco8** [comment]
Log: https://paste.kodi.tv/ujifipipik.kodi

![Captura de pantalla de 2023-11-14 12-11-49](https://github.com/Sandmann79/xbmc/assets/5084042/20b84f9c-22a3-4c42-8543-0bdd2fa2835f)
