### PR TITLE
Kodi 20 compability for browser launcher

### PR DESCRIPTION
**Pull request by altiOnGithub**
After Updating Kodi from 19 to 20 I received the following exception from plugin.program.browser.launcher:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.program.browser.launcher/default.py", line 23, in <module>
                                                       customPath = xbmc.translatePath(addon.getSetting("customPath"))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

The proposed changes fixes browser.launcher to work with Kodi 20.

Please have a look when time permits. Thank you!

### CODE REVIEW

**Comment by Sandmann79** [comment]
Thanks for the PR, but this would break compatibility with Kodi 18/Leia.
A solution with try/except should be the better way:
```
try:
    from xbmcvfs import translatePath
except ImportError:
    from xbmc import translatePath
```
If you would modify that, I will approve the PR

**Comment by altiOnGithub** [comment]
Thank you for your feedback!

Your proposed adoptions have been implemented in this PR.
Please let me know if there is anything else I'm missing.

Thank you for your time!
